
def stop_words_list():

    ENstopWords = ['a', 'about', 'above', 'across', 'after', 'again', 'against', 'all', 'almost', 'alone', 'along',
                 'already', 'also', 'although', 'always', 'among', 'an', 'and', 'another', 'any', 'anybody',
                 'anyone', 'anything', 'anywhere', 'are', 'area', 'areas', "aren't", 'around', 'as', 'ask', 'asked',
                 'asking', 'asks', 'at', 'away', 'b', 'back', 'backed', 'backing', 'backs', 'became', 'because',
                 'become', 'becomes', 'became', 'been', 'before', 'began', 'behind', 'being', 'beings', 'best',
                 'better', 'between', 'big', 'both', 'but', 'by', 'c', 'came', 'can', 'cannot', 'case', 'cases',
                 'certain', 'certainly', 'clear', 'clearly', 'come', 'could', 'd', 'did', 'differ', 'different',
                 'differently', 'do', 'does', 'done', 'down', 'downed', 'downing', 'downs', 'during', 'e', 'each',
                 'early', 'either', 'end', 'ended', 'ending', 'ends', 'enough', 'even', 'evenly', 'ever', 'every',
                 'everybody', 'everyone', 'everything', 'everywhere', 'f', 'face', 'faces', 'fact', 'facts', 'far',
                 'felt', 'few', 'find', 'finds', 'first', 'for', 'four', 'from', 'full', 'fully', 'further',
                 'furthered', 'furthering', 'furthers', 'g', 'gave', 'general', 'generally', 'get', 'gets', 'give',
                 'given', 'gives', 'go', 'going', 'good', 'goods', 'got', 'great', 'greater', 'greatest', 'group',
                 'grouped', 'grouping', 'groups', 'h', 'had', 'has', 'have', 'having', 'he', 'her', 'here',
                 'herself', 'high', 'higher', 'highest', 'him', 'himself', 'his', 'how', 'however', 'i', 'if',
                 'important', 'in', 'interest', 'interested', 'interesting', 'interests', 'into', 'is', 'it',
                 'its', 'itself', 'j', 'just', 'k', 'keep', 'keeps', 'kind', 'knew', 'know', 'known', 'knows',
                 'l', 'large', 'largely', 'last', 'later', 'latest', 'least', 'less', 'let', 'lets', 'like',
                 'likely', 'long', 'longer', 'longest', 'm', 'made', 'make', 'making', 'man', 'many', 'may',
                 'me', 'member', 'members', 'men', 'might', 'more', 'most', 'mostly', 'mr', 'mrs', 'much',
                 'must', 'my', 'myself', 'n', 'necessary', 'need', 'needed', 'needing', 'needs', 'never',
                 'new', 'newer', 'newest', 'next', 'no', 'nobody', 'non', 'noone', 'nor', 'not', 'nothing', 'now',
                 'nowhere', 'number', 'numbers', 'o', 'of', 'off', 'often', 'old', 'older', 'oldest', 'on',
                 'once', 'one', 'only', 'open', 'opened', 'opening', 'opens', 'or', 'order', 'ordered', 'ordering',
                 'orders', 'other', 'others', 'our', 'out', 'over', 'p', 'part', 'parted', 'parting', 'parts', 'per',
                 'perhaps', 'place', 'places', 'point', 'pointed', 'pointing', 'points', 'possible', 'present',
                 'presented', 'presenting', 'presents', 'problem', 'problems', 'put', 'puts', 'q', 'quite', 'r',
                 'rather', 'really', 'right', 'room', 'rooms', 's', 'said', 'same', 'saw', 'say', 'says', 'second',
                 'seconds', 'see', 'seed', 'seeds', 'seeing', 'seem', 'seemed', 'seeming', 'seems', 'sees',
                 'several', 'shall', 'she', 'should', 'show', 'showed', 'showing', 'shows', 'side', 'sides',
                 'since', 'small', 'smaller', 'smallest', 'so', 'some', 'somebody', 'someone', 'something',
                 'somewhere', 'state', 'states', 'still', 'such', 'sure', 't', 'take', 'taken', 'than', 'that',
                 'the', 'their', 'them', 'then', 'there', 'therefore', 'these', 'they', 'thing', 'things',
                 'think', 'thinks', 'this', 'those', 'though', 'thought', 'thoughts', 'three', 'through',
                 'thus', 'to', 'today', 'together', 'too', 'took', 'toward', 'turn', 'turned', 'turning',
                 'turns', 'two', 'u', 'under', 'until', 'up', 'upon', 'us', 'use', 'used', 'uses', 'v',
                 'very', 'w', 'want', 'wanted', 'wanting', 'wants', 'was', 'way', 'ways', 'we', 'well',
                 'wells', 'went', 'were', 'what', 'when', 'where', 'whether', 'which', 'while', 'who',
                 'whole', 'whose', 'why', 'will', 'with', 'within', 'without', 'work', 'worked',
                 'working', 'works', 'would', 'x', 'y', 'year', 'years', 'yet', 'you', 'young', 'younger',
                 'youngest', 'your', 'yours', 'z']

    FRstopWords = ['a', 'abord', 'afin', 'ah', 'ai', 'aie', 'ainsi', 'allo', 'allo', 'allons', 'alors',
                   'apres', 'assez', 'attendu', 'au', 'aucun', 'aucune', 'aucuns', "aujourdhui", 'auquel', 'aura',
                   'auront', 'aussi', 'autre', 'autres', 'aux', 'auxquelles', 'auxquels', 'avaient', 'avais', 'avait',
                   'avant', 'avec', 'avoir', 'ayant', 'bah', 'beaucoup', 'bien', 'bigre', 'bon', 'boum', 'bravo',
                   'brrr', 'ça', 'car', 'ce', 'ceci', 'cela', 'celle', 'celle-ci', 'celle-la', 'celles', 'celui',
                   'celui-ci', 'celui-la', 'cela', 'ces', 'cet', 'cette', 'ceux', 'ceux-ci', 'ceux-la', 'chacun',
                   'chacune', 'chaque', 'cher', 'chere', 'cheres', 'chers', 'chez', 'ci', 'comme', 'comment', 'contre',
                   'd', "dabord", "daccord", "dailleurs", "dun", 'dune', 'dans', 'de', 'dedans', 'dehors', 'delà',
                   'depuis', 'derriere', 'des', 'des', 'desormais', 'desquelles', 'desquels', 'dessous', 'dessus',
                   'devant', 'devers', 'devra', 'devrait', 'differentes', 'differents', 'divers', 'diverses',
                   'dix', 'doit', 'doivent', 'donc', 'dont', 'douze', 'du', 'duquel', 'durant', 'des', 'elle',
                   'elles', 'en', 'encore', 'entre', 'envers', 'environ', 'es', 'essai', 'est', 'et', 'etaient',
                   'etais', 'etait', 'etant', 'etante', 'etants', 'etantes', 'etc', 'etions', 'ete', 'eetee', 'etees',
                   'etes', 'etes', 'etre', 'eu', 'eue', 'eues', 'eumes', 'eut', 'eux', 'eurent', 'eus', 'eusse',
                   'eussent', 'eusses', 'eussiez', 'eussions', 'ex', 'fais', 'fait', 'faite', 'faites', 'faits',
                   'falloir', 'fas', 'fasse', 'fassent', 'fassiez', 'fassions', 'faudra', 'faudrait', 'faut', 'fi',
                   'flac', 'fors', 'furent', 'fus', 'fusse', 'fussent', 'fusses', 'fussiez', 'fussions', 'fût',
                   'fûmes', 'futes', 'gens', 'ha', 'he', 'he', 'hein', 'hem', 'hep', 'hi', 'ho', 'holà', 'hop',
                   'hormis', 'hors', 'hou', 'houp', 'hue', 'hui', 'huit', 'hum', 'hurrah', 'he', 'helas', 'i',
                   'ici', 'il', 'ils', 'importe', 'j', 'je', 'jusqu', 'jusque', 'juste', 'l', 'la', 'laquelle',
                   'las', 'le', 'lequel', 'les', 'lès', 'lesquelles', 'lesquels', 'leur', 'leurs', 'loin',
                   'longtemps', 'lors', 'lorsque', 'lui', 'lès', 'm', 'ma', 'maint', 'mais', 'malgre', 'me',
                   'même', 'mêmes', 'merci', 'mes', 'mien', 'mienne', 'miennes', 'miens', 'mille', 'mince', 'mine',
                   'moi', 'moins', 'mon', 'mot', 'moyennant', 'n', 'na', 'ne', 'neanmoins', 'neuf', 'neuvième',
                   'ni', 'nombreuses', 'nombreux', 'nommes', 'non', 'nos', 'notre', 'notre', 'nôtres', 'nous',
                   'nul', 'o', 'oh', 'ohe', 'ole', 'olle', 'on', 'ont', 'onze', 'onzième', 'ore', 'ou', 'où',
                   'ouais', 'oui', 'outre', 'ouvert', 'ouverte', 'ouverts', 'o|', 'p', 'paf', 'pan', 'par', 'parmi',
                   'partant', 'particulier', 'particuliere', 'particulierement', 'pas', 'passe', 'pendant',
                   'personne', 'peu', 'peut', 'peuvent', 'peux', 'pff', 'pfft', 'pfut', 'piece', 'pire', 'pis',
                   'plein', 'plouf', 'plupart', 'plus', 'plusieurs', 'pour', 'pourquoi', 'premier', 'première',
                   'premierement', 'près', 'proche', 'psitt', 'puisque', 'qu', 'quand', 'quant', 'quanta',
                   'quant-a-soi', 'quarante', 'quatorze', 'quatre', 'quatre-vingt', 'quatrieme', 'quatriemement',
                   'que', 'quel', 'quelconque', 'quelle', 'quelles', 'quelquun', 'quelque', 'quelques', 'quels',
                   'qui', 'quiconque', 'quinze', 'quoi', 'quoique', 'r', 'revoici', 'revoila', 'rien', 's', 'sa',
                   'sacrebleu', 'sait', 'sans', 'sapristi', 'sauf', 'se', 'seize', 'selon', 'seront', 'ses', 'seul',
                   'seule', 'seulement', 'si', 'sien', 'sienne', 'siennes', 'siens', 'sinon', 'six', 'soi', 'soi-meme',
                   'soient', 'sois', 'soit', 'soixante', 'sommes', 'son', 'sont', 'sous', 'souvent', 'soyez', 'soyons',
                   'stop', 'suis', 'suite', 'sur', 'sûr', 't', 'ta', 'tac', 'tandis', 'tant', 'tardive', 'te', 'tel',
                   'telle', 'tellement', 'telles', 'tels', 'tenant', 'tente', 'tes', 'tic', 'tien', 'tienne',
                   'tiennes', 'tiens', 'toc', 'toi', 'toi-même', 'ton', 'tonte', 'tontes', 'trop', 'très', 'trente',
                   'trente-deux', 'troisieme', 'troisiemement', 'trois', 'tres', 'trop', 'tsoin', 'tsouin', 'tu',
                   'te', 'u', 'un', 'une', 'unes', 'uns', 'v', 'va', 'vais', 'vas', 've', 'vers', 'via', 'vif', 'vifs',
                   'vingt', 'vivement', 'vive', 'vives', 'vlan', 'voici', 'voila', 'vont', 'vos', 'votre', 'votre',
                   'votres', 'vous', 'voute', 'vouloir', 'voulons', 'voulurent', 'voulumes', 'voulut', 'voulaient',
                   'voudrais', 'voudriez', 'voudrons', 'voudrions', 'voudrez', 'voudras', 'voudrai', 'vrai', 'vrais',
                   'vraiment', 'vu', 've', 'votre', 'votres', 'w', 'x', 'y', 'z', 'zut', 'a', 'ça', 'es', 'etant',
                   'ete', 'etre', 'o']

    return ENstopWords, FRstopWords
