#[server]
#port = 8501
#enableCORS = false
#enableXsrfProtection = true
#headless = true

#[browser]
#serverAddress = "localhost"
#serverPort = 8501
#gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

#[runner]
#magicEnabled = true
#installTracer = false

[logger]
level = "info"
